### ISSUE TITLE
Update Socket.io dependency to new classpath

### ISSUE THREAD

**Issue by ligol** [taplytics/Taplytics-Android-SDK#13]
Hi,

Have you any plan to update your socket.io dependency to their last version?
In order to use the new package name they choose?

In the same way, do you have any plan to separate this part of the SDK in a sub-part, in order to don't bundle this dependency in release if we don't need them?

Thanks in advance.

**Comment by VicV** [comment]
Hey @ligol ,

Its up to you to decide which socket.io version to use. Preferably you would choose the latest version.

We always point to the latest in our build.gradle files.

If you are looking at our jarfile, we will be removing that shortly.

Please use our gradle dependency. 

Thanks.

**Comment by ligol** [comment]
The fact is the artifact was totally changed by the developer of the socket.io lib used.

Before:

    <dependency>
      <groupId>com.github.nkzawa</groupId>
      <artifactId>socket.io-client</artifactId>
      <version>+</version>
      <scope>compile</scope>
    </dependency>

After: 

<dependencies>
  <dependency>
    <groupId>io.socket</groupId>
    <artifactId>socket.io-client</artifactId>
    <version>0.6.2</version>
  </dependency>
</dependencies>

After a try with the new dependency, the SDK didn't work anymore due to an error ClassNotFoundException.

**Comment by VicV** [comment]
Ahhh. Didn't notice the new changes. 

We'll update this shortly, but we'll have to notify all of our clients about this change first as it wont be automatic.

Thanks!

**Comment by ligol** [comment]
HI,

Do you have any news about the update?

**Comment by VicV** [comment]
Hi @ligol ,

Doing this right now. Will get back to you by the end of the day.

**Comment by VicV** [comment]
@ligol doing this right now, sorry for the delay.

The delay is due to the fact that we are currently making socket-io a non-necessary dependency for release builds if you do not wish to include it.

**Comment by ligol** [comment]
Hi,

No problem, if socket-io is optional that would be perfect.
Good luck with that.

**Comment by VicV** [comment]
Hey Ligol,

All done. Going to put it in the next release.

**Comment by VicV** [comment]
@ligol , so sorry for the delay. Tried to bundle a bunch of things into a big release and it ended up taking up a lot of time. Will have to put those changes in a different release, BUT, 1.7.0 has what you're looking for. 

Here you go: https://github.com/taplytics/Taplytics-Android-SDK/releases/tag/1.7.0

**Comment by ligol** [comment]
Thanks for the release, it's now perfect
