### ISSUE TITLE
Can we get a version that uses Retrofit?

### ISSUE THREAD

**Issue by jkane001** [taplytics/Taplytics-Android-SDK#14]
For those of us that already use a library for networking (i.e. Retrofit), it's a little sad to ALSO import the Volley library. Can we get an alternate library that relies on Retrofit instead of Volley?

FWIW, many libraries that rely on networking will use native libraries by default, and then allow adding on support for third-party networking libraries as add-ons, rather than defaulting to one particular library.

**Comment by VicV** [comment]
Purging out volley is on the list, yep.

**Comment by jkane001** [comment]
Awesome!

**Comment by VicV** [comment]
Volley is in there because it was the fastest way to get off the ground with multipart uploads. 

We recently removed a lot of dependencies (surrounding socket stuff, so its not necessary in release anymore). 

We wont be doing a retrofit build (not 100% sure), but I'll with 100% certainty be removing Volley in the near future. Still working on other things first! 

Will keep this open and let you know when it happens.

**Comment by manjunathc23** [comment]
+1

**Comment by VicV** [comment]
@jkane001 @manjunathc23 

Sorry for the massive delay on this one. Started working on it today, should be good to go in a few days time.

**Comment by VicV** [comment]
I guess for clarification, I _am_ putting retrofit in.

**Comment by VicV** [comment]
Update: 

Things are moving along. 

It's taking so long because I am adding the ability to decide to use volley **or** retrofit AND making a comprehensive test suite around that to ensure that both libraries result in the same behaviour.

**Comment by VicV** [comment]
Code is in. Doing manual testing on real projects now to confirm everything is in order and it should be out EOD today or first thing tomorrow morning.

Will be release 1.8.0

**Comment by VicV** [comment]
@jkane001 I hope you're okay with Retrofit2 instead of Retrofit.

**Comment by jkane001** [comment]
@VicV - Retrofit2 is perfect, can't wait to update!

**Comment by VicV** [comment]
[Here you go](https://github.com/taplytics/Taplytics-Android-SDK/releases/tag/1.8.0)

Please let me know how it works or if you are seeing any issues.

cc @jkane001 @manjunathc23
