### ISSUE TITLE
incompatible types: TaplyticsRunningExperimentsListener is not a functional interface

### ISSUE THREAD

**Issue by raymondctc** [taplytics/Taplytics-Android-SDK#21]
We are trying to include Taplytics 1.9.7 to our app, however when we try to compile, it fails:
```
incompatible types: TaplyticsRunningExperimentsListener is not a functional interface
```
Falling back to 1.9.5 seems good. FYI, We have included retrolambda in our app.

**Comment by VicV** [comment]
@raymondctc its not an interface anymore.

**Comment by VicV** [comment]
It is a class with a method, called as a simple callback.

**Comment by VicV** [comment]
Let me know if that helps out. It has some logic behind it internally now so I switched it up.

**Comment by raymondctc** [comment]
Ah... I see, thanks @VicV, I'll now close this issue

**Comment by VicV** [comment]
@raymondctc in 1.10.4 it has been replaced again as an interface, FYI.
