### ISSUE TITLE
More proguard issues?

### ISSUE THREAD

**Issue by jkane001** [taplytics/Taplytics-Android-SDK#22]
I'm having trouble getting a release build to work, and on debugging the issue, I'm seeing this line in the stacktrace:

Failed to read stored entry 'com/taplytics/vicu±a.class'

I see that a release a couple days ago made it so we can't proguard Taplytics anymore, but to my knowledge, I can only tell Proguard NOT to mess with a library, I don't explicitly tell it which libraries to compress. So do I need to include something in the config to tell it to leave Taplytics alone?

Thanks!

**Comment by jkane001** [comment]
Never mind, I think it's a separate library causing the issue

**Comment by VicV** [comment]
@jkane001 did you figure this out?

Turns out I have a word in my dictionary called 'vicuña' so it will generate a 'vicuña.smali'

Doesn't seem to be an issue generally, but did you figure out what library had this issue?

**Comment by jkane001** [comment]
I haven't figured it out totally - it seems to only be a problem on gradle
plugin 2.2.0-alpha5, and I'm thinking it's actually caused by certain
characters in the code (I guess), and I think it might be yours AND another
that cause the error, and so when I remove both, it's all good, but if I
put either back, it fails. However, for now, I've simply reverted back to
alpha4, and all is well.

If you want me to try it with a version that doesn't have that word in it,
i can, and see if that changes the issue on alpha5.

Thanks!
J
