### ISSUE TITLE
NullPointerException reported by Firebase Crash Reporter

### ISSUE THREAD

**Issue by avioraboo** [taplytics/Taplytics-Android-SDK#38]
I have no idea how to reproduce this bug but it occurs 8 - 17 times a day.

Exception java.lang.RuntimeException: An error occurred while executing doInBackground()
android.os.AsyncTask$3.done (AsyncTask.java:318)
java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:354)
java.util.concurrent.FutureTask.setException (FutureTask.java:223)
java.util.concurrent.FutureTask.run (FutureTask.java:242)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)
arrow_drop_down
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.taplytics.anteater com.taplytics.ant.aardvark()' on a null object reference
com.taplytics.dotterel.aardvark (SourceFile:224)
com.taplytics.dotterel.aardvark (SourceFile:26)
com.taplytics.dotterel$albatross.aardvark (SourceFile:260)
com.taplytics.dotterel$albatross.doInBackground (SourceFile:255)
android.os.AsyncTask$2.call (AsyncTask.java:304)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)

**Comment by VicV** [comment]
Hey there, thanks for reporting this.

What version of the SDK are you currently running?

**Comment by VicV** [comment]
@avioraboo Let us know so we can get started on helping you out!

**Comment by avioraboo** [comment]
Sorry it took me awhile, I'm using Android SDK version 1.21.0

**Comment by avioraboo** [comment]
@VicV Hello, did you saw my last message?

**Comment by cdruxerman** [comment]
Hi @avioraboo sorry for the delay, we received this. Also, would you happen to have a public crashlytics link you could share to give us further context?

**Comment by avioraboo** [comment]
We are using Firebase as the crash reporter, so I don't have a link for you.

**Comment by cdruxerman** [comment]
Ok, not a problem, just thought I'd check
