### ISSUE TITLE
Incompatible with R8 (Proguard replacement)

### ISSUE THREAD

**Issue by jkane001** [taplytics/Taplytics-Android-SDK#45]
Google's previewing a replacement for Proguard called R8 (https://developer.android.com/studio/preview/features/), and it appears I cannot build a release w/ shrinking enabled as long as I've got Taplytics in my code.

Error I get is:

Error in C:\Users\jkane\.gradle\caches\transforms-1\files-1.1\taplytics-1.24.1.aar\9e5a6b0cabb94591e1188a32c131b082\proguard.txt:
  Expected char '-' at C:\Users\jkane\.gradle\caches\transforms-1\files-1.1\taplytics-1.24.1.aar\9e5a6b0cabb94591e1188a32c131b082\proguard.txt:4:17
-keepattributes Exceptions,LineNumberTable,Signature,*Annotation*,SourceFile,EnclosingMethod

I tried invalidating cache, and still get the same error on prod build.

**Comment by cdruxerman** [comment]
Hi @jkane001 thank you for bringing this to our attention. I'll have our team look into it and get back to you

**Comment by kavitasookrah** [comment]
Hey @jkane001,

Sorry for the delayed response to this. Can you give us any additional details on the the set up - specifically:

- Any details on how the configuration of your project is set up? 
- How is the R8 set up? 
- Is this consistently reproducible on your app?

Any additional info you can provide would help! Thanks very much, 

Kavita

**Comment by VicV** [comment]
Confirmed this is no longer an issue. Thanks!
